# Generated by Django 3.1.7 on 2021-05-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_auto_20210521_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
